#! /bin/sh

if ! grep -qP '^[a-zA-Z]+(\([a-zA-Z]+\))?!?: .*$' "$1"; then
	echo "Invalid format. The commit message must comply with the conventional commit specification. Please fix and try again." >&2
	exit 1
fi
